device:
  use_cuda: true
g: 9.807
input_vars:
- precip
- et
- A_bucket
- A_spigot
- H_bucket
- H_spigot
- K_infiltration
- ET_parameter
model:
  batch_size: 512
  hidden_state_size: 16
  input_size: 8
  learning_rate:
    gamma: 0.9
    start: 0.1
    step_size: 2
  num_classes: 2
  num_epochs: 5
  seq_length: 32
output_vars:
- q_spigot
- q_overflow
synthetic_data:
  test:
    bucket_attributes:
      A_bucket:
      - 1.0
      - 2.0
      A_spigot:
      - 0.1
      - 0.2
      ET_parameter:
      - 7
      - 9
      H_bucket:
      - 5.0
      - 6.0
      H_spigot:
      - 1.0
      - 3.0
      K_infiltration:
      - 1e-7
      - 1e-9
    n_buckets: 3
    noise:
      et: 0.1
      head: 0.1
      pet: 0.1
      q: 0.1
    num_records: 400
    rain_depth:
      Heavy:
      - 2
      - 8
      Light:
      - 0
      - 2
    rain_probability:
      Heavy:
      - 0.2
      - 0.3
      Light:
      - 0.5
      - 0.8
      None:
      - 0.6
      - 0.7
  train:
    bucket_attributes:
      A_bucket:
      - 1.0
      - 2.0
      A_spigot:
      - 0.1
      - 0.2
      ET_parameter:
      - 7
      - 9
      H_bucket:
      - 5.0
      - 6.0
      H_spigot:
      - 1.0
      - 3.0
      K_infiltration:
      - 1e-7
      - 1e-9
    n_buckets: 10
    noise:
      et: 0.01
      head: 0.01
      pet: 0.01
      q: 0.01
    num_records: 300
    rain_depth:
      Heavy:
      - 2
      - 8
      Light:
      - 0
      - 2
    rain_probability:
      Heavy:
      - 0.2
      - 0.3
      Light:
      - 0.5
      - 0.8
      None:
      - 0.6
      - 0.7
  val:
    bucket_attributes:
      A_bucket:
      - 1.0
      - 2.0
      A_spigot:
      - 0.1
      - 0.2
      ET_parameter:
      - 7
      - 9
      H_bucket:
      - 5.0
      - 6.0
      H_spigot:
      - 1.0
      - 3.0
      K_infiltration:
      - 1e-7
      - 1e-9
    n_buckets: 20
    noise:
      et: 0.01
      head: 0.4
      pet: 0.01
      q: 0.01
    num_records: 150
    rain_depth:
      Heavy:
      - 2
      - 8
      Light:
      - 0
      - 2
    rain_probability:
      Heavy:
      - 0.2
      - 0.3
      Light:
      - 0.5
      - 0.8
      None:
      - 0.6
      - 0.7
time_step: 1
