# Configuration file for Deep Bucket Lab
g: 9.807
time_step: 1
model:
  num_classes: 2
  input_size: 9
  hidden_state_size: 16
  num_layers: 8
  num_epochs: 15
  batch_size: 256
  seq_length: 24
  learning_rate:
    start: 0.1
    end: 0.01
    num_steps: 5

device:
  use_cuda: true

synthetic_data:
  train:
    n_buckets: 50
    num_records: 100
    bucket_attributes:
      A_bucket: [1.0, 2.0]
      A_spigot: [0.1, 0.2]
      H_bucket: [5.0, 6.0]
      H_spigot: [1.0, 3.0]
      K_infiltration: [1e-7, 1e-9]
      ET_parameter: [7, 9]
    rain_probability:
      None: [0.6, 0.7]
      Light: [0.5, 0.8]
      Heavy: [0.2, 0.3]
    rain_depth:
      Light: [0, 2]
      Heavy: [2, 8]
    noise:
        pet: 0.1
        et: 0.1
        q: 0.1
        head: 0.1
  val:
    n_buckets: 10
    num_records: 100
    bucket_attributes:
      A_bucket: [1.0, 2.0]
      A_spigot: [0.1, 0.2]
      H_bucket: [5.0, 6.0]
      H_spigot: [1.0, 3.0]
      K_infiltration: [1e-7, 1e-9]
      ET_parameter: [7, 9]
    rain_probability:
      None: [0.6, 0.7]
      Light: [0.5, 0.8]
      Heavy: [0.2, 0.3]
    rain_depth:
      Light: [0, 2]
      Heavy: [2, 8]
    noise:
        pet: 0.1
        et: 0.1
        q: 0.1
        head: 0.1
  test:
    n_buckets: 10
    num_records: 100
    bucket_attributes:
      A_bucket: [1.0, 2.0]
      A_spigot: [0.1, 0.2]
      H_bucket: [5.0, 6.0]
      H_spigot: [1.0, 3.0]
      K_infiltration: [1e-7, 1e-9]
      ET_parameter: [7, 9]
    rain_probability:
      None: [0.6, 0.7]
      Light: [0.5, 0.8]
      Heavy: [0.2, 0.3]
    rain_depth:
      Light: [0, 2]
      Heavy: [2, 8]
    noise:
        pet: 0.1
        et: 0.1
        q: 0.1
        head: 0.1